repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
  - id: flake8
    exclude: 'solutions'

- repo: https://github.com/pre-commit/mirrors-isort
  rev: master
  hooks:
  - id: isort
    exclude: 'solutions'
    additional_dependencies:
    - 'toml'

- repo: https://github.com/python/black
  rev: master
  hooks:
  - id: black
    exclude: 'solutions'

- repo: local
  hooks:
  - id: clean-notebooks
    name: clean-notebooks
    entry: ./scripts/clean-notebooks.sh
    language: script
    files: \.ipynb$
