[tool.poetry]
name = "stylo"
version = "0.9.1"
description = "Drawing images with a blend of Python and Mathematics"
readme = "README.md"

authors = ["Alex Carney <alcarneyme@gmail.com>"]

license = "MIT"

homepage = "https://stylo.readthedocs.io/en/latest/"
repository = "https://github.com/alcarney/stylo"
documentation = "https://stylo.readthedocs.io/en/latest/"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Multimedia :: Graphics"
]

include = ["CHANGES.rst"]

[tool.poetry.dependencies]
python = "^3.5"

numpy = "*"
matplotlib = "*"
hypothesis = "*"
Pillow = "*"
pytest = "*"
tqdm = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
hypothesis = "*"
sphinx = "^1.8"
sphinx-stylo = "^0.1.1"
topos-theme = "^0.0.11"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
