[build-system]
requires = ["setuptools >= 35.0.2", "wheel >= 0.29.0"]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = [
  "docs",
  "docs/*",
  ".pre-commit-config.yaml",
  "azure-pipelines.yml",
  "scripts",
  "scripts/*",
  ".coveragerc",
  ".flake8",
  "*.ipynb_checkpoints",
  "*.ipynb_checkpoints/*",
  "tests",
  "tests/*"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = pkg, lint, docs, py{36,37}, py{36,37}-doc
isolated_build = True

[testenv]
deps =
     .[all]
     pytest
     pytest-cov
     pytest-azurepipelines
commands =
    pytest -q --cov=stylo --cov-report html {posargs}

[testenv:docs]
deps =
     sphinx
     sphinx_rtd_theme
commands =
    sphinx-build -M linkcheck docs docs/_build -E -a -j auto {posargs}
    sphinx-build -M html docs docs/_build -E -a -j auto {posargs}

[testenv:docs-preview]
deps =
     {[testenv:docs]deps}
     sphinx-autobuild
usedevelop = True
commands =
     sphinx-autobuild docs docs/_build/html -E -a {posargs}

[testenv:lint]
deps =
     pre-commit
     jupyter
commands =
    pre-commit run --all-files

[testenv:pkg]
deps =
     check-manifest
     wheel
commands =

     check-manifest
     python setup.py sdist bdist_wheel
"""