[build-system]
requires = ["setuptools >= 35.0.2", "wheel >= 0.29.0"]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = [
  "docs",
  "docs/*",
  ".pre-commit-config.yaml",
  "azure-pipelines.yaml",
  "scripts",
  "scripts/*",
  ".coveragerc",
  ".flake8",
  "*.ipynb_checkpoints",
  "*.ipynb_checkpoints/*",
  "tests",
  "tests/*"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = lint, docs, py37

[testenv]
deps =
     pytest
     pytest-cov
commands =
    pytest -q --cov=stylo {posargs}

[testenv:docs]
deps =
     sphinx
     sphinx_rtd_theme
usedevelop = True
commands =
    sphinx-build -M linkcheck docs docs/_build -E -a -j auto
    sphinx-build -M html docs docs/_build -E -a -j auto

[testenv:lint]
deps =
     pre-commit
     jupyter
commands =
    pre-commit run --all-files

[testenv:pkg]
deps =
     check-manifest
     wheel
commands =

     check-manifest
     python setup.py sdist bdist_wheel
"""