name: Blog Build
on:
  # <trigger-push>
  push:
    branches:
    - develop
    paths:
    - 'blog/**'
  # </trigger-push>
  # <trigger-pr>
  pull_request:
    branches:
    - develop
    paths:
    - 'blog/**'
  # </trigger-pr>
  # <trigger-cron>
  schedule:
    - cron: '0 6 * * *'
  # </trigger-cron>

jobs:
  # <build-job>
  Build:
    runs-on: ubuntu-latest
  # </build-job>
    steps:

    # <build-job-setup>
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Setup Environment
      run: |
        python --version

        python -m pip install --upgrade pip
        python -m pip install --pre arlunio
        python -m pip install -r blog/requirements.txt
    # </build-job-setup>

    # <build-job-blog>
    - name: Build Gallery
      run: |
        cd docs
        make nbgallery

        ls -1 _build/nbgallery/examples/
        cp _build/nbgallery/examples/*.ipynb ../blog/src/gallery

        cd ../blog
        python gallery.py

    # </build-job-blog>
    # <build-job-deploy>
    - name: Publish Release Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'blog'
        path: blog/public
      if: github.event_name == 'pull_request'

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: develop
        BRANCH: gh-pages
        FOLDER: blog/public
      if: github.event_name != 'pull_request'
    # </build-job-deploy>
