name: Python Linting

# <trigger>
on:
  pull_request:
    branches:
    - develop
    - master
    paths:
    - 'arlunio/**'
    - 'blog/**'
    - 'tests/**'
    - 'setup.py'
# </trigger>

jobs:
  # <lint-job>
  Lint:
    runs-on: ubuntu-latest
  # </lint-job>
    steps:
    # <lint-job-steps>
    - uses: actions/checkout@v1

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Setup Environment
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]

    - name: Lint
      run: |
        ls -a
        pre-commit run --all-files
    # </lint-job-steps>
    # <lint-job-onerror>
    - name: Show Fixes
      run:
        git diff
      if: ${{ failure() }}
    # </lint-job-onerror>
